An 5365/add credit card scanning
Freshly/braintree-android-drop-in pull request #1
Opened 2021-06-15 15:47 UTC by louislamgo

## [AN-5365](https://freshly.atlassian.net/browse/AN-5365)

## What's this PR do?
- add paycard lib to braintree
- add scan featurte

## Checklist

- [x] The title of this PR is the same as the story.
- [x] The pull request is < 300 LOC.
- [x] The pull request doesn't contain unneeded changes (IDE settings, code style config).
- [x] I have tested this myself.
- [x] I have added all necessary labels (WIP,review, etc).
- [x] I have added the correct milestone.

2021-06-15 17:08 UTC, Vadimkomis approved these changes
Looks good to me 👍 Great job @louislamgo

2021-06-17 13:13 UTC, vladislavbakan requested changes
Look good 👍 
But i think it contains some unneeded changes. As it's fork we should make as little changes as possible

2021-06-17 13:13 UTC, vladislavbakan commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +        if (itemId == R.id.scan) {
I suppose, we can use `when`

2021-06-17 13:13 UTC, vladislavbakan commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +    protected void onActivityResult(int requestCode, int resultCode, @Nullable @org.jetbrains.annotations.Nullable Intent data) {
I think we've imported wrong package above

2021-06-17 13:13 UTC, vladislavbakan commented on Drop-In/src/main/res/drawable/ic_camera.xml
> +<vector android:height="24dp" android:tint="#FFFFFF"
👍

2021-06-17 13:13 UTC, vladislavbakan commented on Drop-In/build.gradle
> +apply plugin: 'com.github.dcendents.android-maven'
Why do we need this?

2021-06-17 13:13 UTC, vladislavbakan commented on Drop-In/src/main/res/menu/bt_scan.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android"
👍  But i think menu file should have a different name. Why do we use `bt_` prefix?

2021-06-17 13:13 UTC, vladislavbakan commented on build.gradle
> +        maven { url "https://jitpack.io" }
Why do we need this?

2021-06-21 06:21 UTC, louislamgo commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +        if (itemId == R.id.scan) {
hm, this is java file, so I was trying to use `switch` but it gave me a warning.
```
  switch (item.getItemId()) {
            case R.id.scan:
  ...
```
`Resource IDs cannot be used in a switch statement in Android library modules`

2021-06-21 06:22 UTC, louislamgo commented on Drop-In/build.gradle
> -afterEvaluate {
sorry, I added back based on https://developer.android.com/studio/build/maven-publish-plugin#groovy. 
it is required for `creating a publication for the release and debug build variants of an AAR library.

2021-06-21 06:23 UTC, louislamgo commented on Drop-In/build.gradle
> +apply plugin: 'com.github.dcendents.android-maven'
correct. it is abondoned. 👍 removed.

2021-06-21 06:25 UTC, louislamgo commented on Drop-In/src/main/res/menu/bt_scan.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android"
very nice catch. without `bt_`, it gives me warning because ` resourcePrefix 'bt_` is set.

2021-06-21 13:30 UTC, louislamgo commented on build.gradle
> +        maven { url "https://jitpack.io" }
removed

2021-06-21 13:31 UTC, louislamgo commented on Demo/build.gradle
> +repositories {
can't build the project without it. it gives me `Could not resolve all artifacts for configuration ':Demo:debugRuntimeClasspath'.`.

2021-06-22 15:42 UTC, vladislavbakan commented on Demo/build.gradle
> +repositories {
Ok cool 👍

2021-06-22 15:45 UTC, vladislavbakan commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +        if (itemId == R.id.scan) {
Oh, yeah, that's not Kotlin 😢

2021-06-22 15:47 UTC, vladislavbakan commented on build.gradle
> -version '5.2.2-SNAPSHOT'
I'm not sure, we should change that, because we do our change based on specific version

2021-06-22 15:47 UTC, vladislavbakan commented on Drop-In/src/main/res/menu/bt_scan.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android"
Which warning do you mean? it's just file name

2021-06-24 06:55 UTC, louislamgo commented on Drop-In/src/main/res/menu/bt_scan.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android"
if you will do a global search you see `resourcePrefix 'bt_` in the drop-in gradle file. 
After I change the menu file to `scan` then gives me an error.
![image](https://user-images.githubusercontent.com/8280480/123216445-8d421300-d497-11eb-9957-8b70aefe7f0f.png)

2021-06-24 07:06 UTC, louislamgo commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInActivity.java
> +import androidx.annotation.VisibleForTesting;
auto formated. 👍

2021-06-24 20:08 UTC, vladislavbakan approved these changes
Awesome 👍 
Great work Yi 👍

2021-06-24 20:08 UTC, vladislavbakan commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +        boolean isEnable = getIntent().getBooleanExtra(EXTRA_SCAN_FEATURE_FLAG, false);
👍 Cool

2021-06-24 20:09 UTC, vladislavbakan commented on Drop-In/src/main/res/menu/bt_scan.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android"
Ok, got it, thanks 👍

2021-06-24 20:09 UTC, vladislavbakan approved these changes

2021-06-24 20:10 UTC, vladislavbakan commented
@afomich @pavelkharetskifreshly could you please take a look at this PR?

2021-06-28 10:30 UTC, pavelkharetskifreshly approved these changes
👍 Cool 👍

2021-06-28 10:30 UTC, pavelkharetskifreshly commented on Drop-In/build.gradle
>      publishing {
👍

2021-06-28 10:30 UTC, pavelkharetskifreshly commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +    private void setupScanButton(Menu menu) {
👍

2021-06-29 10:38 UTC, afomich approved these changes
Looks good 👍

2021-06-29 10:38 UTC, afomich commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
👍

2021-06-29 10:38 UTC, afomich commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +            startActivityForResult(intent, REQUEST_CODE_SCAN_CARD);
👍

2021-06-29 10:38 UTC, afomich commented on Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java
> +            cards.pay.paycardsrecognizer.sdk.Card card =
👍

2021-06-29 13:28 UTC, merged